// Generated by scripts/generate-update-keys.js
export const UPDATE_PUBLIC_KEY = "-----BEGIN PUBLIC KEY-----\nMCowBQYDK2VwAyEA456Jh+SGvfX68bpkqu2/Rr/8VApwQNQ8UWa2bYNdCp8=\n-----END PUBLIC KEY-----\n";
